# Language/versions
language: node_js
node_js:
  - "node"
	- "lts/*"
  - "8"
  - "10"
  - "12"

# Notifications
notifications:
 email:
   - notify+mail@tedeh.net

after_success:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
